[package]
name = "rust-reverse-proxy-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
dotenv = "0.15.0"
lazy_static = "1.4.0"
reqwest = "0.11.14"
tokio = "1.25.0"